In [ ]:
 invnochk=re.search('r(^.+SP-.*)|(^SP-.*)',t,re.I)
            if getrefnochk:
                #print(t) 
                if re.search(r'(SP-.*)',t,re.I):
                    getrefno= re.search(r'(Mb_.*)(SP-1.*)',t,re.I)
                    refno=getrefno.group(1)
                    invno=getrefno.group(2)
                else:
                    refno=getrefnochk.group(1)
                    #|(\s*[\d]*\s*[\d]*
                    
                    (.*)(?P<ref>Mb_.*)(?P<inv>SP-1(\s*)([\d]*))(\s*)(?P<cour>\w+|(\w+\s*\w+)|(\w+\s*\w+\s*\w+))(\s*)(?P<conno>\w-([\d]*|\d*\D*\d*))(\s*)(?P<dd>[\d]*\D*[\d]*\s)(?P<dispby>(\w+) (\w+))(\W*)(?P<sd>\w+\s*\d*\s*\d*)(\W*)(?P<stime>\d*:\d*:\d*)(\s*)(?P<am>(\w{2}))(\W*)(?P<cname>\w+)(\W*)(?P<email>(\w+\W*\w*\W*@(.*)com))(\W*)(?P<Aname>(\w+)\W*(\w+)\W*(\w*))(\W*)(?P<Add>\d*(.*)(\d{5}))

In [56]:
import os
import hashlib 
import re
from collections import Counter
File='SA_001_102.txt'
path='/home/krishna/Desktop/'
text=[]
datadict={}
start=0
end ='N'
L = []
M = []
N = []
W = []

with open(os.path.join(path,File),'r') as rf:
    for i in rf :
        if re.search("Mb_Sales-Med",i) :
                start+=1
                if start >1:
                    datadict[start]=text
                    text=[]
                    #text.append(i)
        text.append(i)
    for k,v in datadict.items():
        orderdet=''
        for t in v:
            #getrefno=re.search( r'(.*)(\s)([\D]-[\d]{4,})(\s)(.*)', t, re.M|re.I)
            orderdet+=t.replace('\n', ' ').replace('\r', '')
        #getgrps=re.search(r'(.*)(Mb_.*)(\s)(SP-1(\s*)((\d*)|((\d*)(\D*)(\d*))))(\s)(.*)',orderdet,re.I)
        getgrps=re.search(r'(.*)(?P<ref>Mb_.*)(\W*)(?P<inv>SP-1(\s*)([\d]*))(\W*)(?P<cour>(\w+\s+\w+\s+\w*)|(\w+)|(\w+\s+\w*))(\W*)(?P<cours>T-1(\s*))(.*)',orderdet,re.I)
        #print(orderdet) 
        if getgrps:
            #print(getgrps.group(2))
            print(getgrps.group('ref'))
            print(getgrps.group('inv'))
            print(getgrps.group('cour'))
            print(getgrps.group('cour'))
            a= getgrps.group('ref')
            b= getgrps.group('inv')
            c= getgrps.group('cour')
            #d= getgrps.group('cour_num')
            L.append(a)
            M.append(b)
            N.append(c)
            #W.append(d)
            #print(getgrps.groups())
            print('\n')

Mb_Sales-Med-N p#-144604#1 1 @ns PUCIa#00000614894 —
SP-1 70010013941
THE MITRE CORPORATION
THE MITRE CORPORATION


Mb_Sales-Med-N p#-144604#1 1 @ns- PUCIa#-000001 70633
SP-1 700100175450
THOMSON FINANCIAL
THOMSON FINANCIAL


Mb_Sales-Med-Np#-144604#11 @as PUCIa#-00000687290
SP-17700100166033
TANGOSOL INC
TANGOSOL INC


Mb_Sales-Med-N p#-144604#1 1 @ns- PUCI a#-0000061 39: ‘SP-177001I00H4 7545 ARIES CARGO A-1 701431858 Torp ‘Mar09 07 23405PM  LomQuitzon Brandyn Mohr@yahoo.com Alexandre Gislason 334 HIRTHE PARKS SCHROEDERMOUTH MAINE 46187 174460-7101 Discover 3784172642034 S4 9-5 1-10 7-5 91 8  = a ee eae ec eevee
SP-1 770010011
86  HE MUNICENTER
86  HE MUNICENTER

In [54]:
import pandas as pd

In [41]:
df = pd.DataFrame(L)
df1 = pd.DataFrame(M)
df2 = pd.DataFrame(N)
df3 = pd.DataFrame(W)

In [44]:
df.columns = ['Refno']
df1.columns = ['courier_no']
df2.columns =['Courier_name']
df3.colums =['Courier_number']

In [48]:
df3

Empty DataFrame
Columns: []
Index: []

In [46]:
main = pd.concat([df,df1,df2,df3],axis=1)

In [31]:
main

,Refno,courier_no,Courier_name
0,Mb_Sales-Med-N p#-144604#1 1 @ns- PUCIa#-00000...,SP-1 770010015876,ANEXINET
1,Mb_Sales-Med-N p#-144604#1 1 @ns PUCIa#-000001...,SP-1 770010011,8862 THOMSON FINANCIAL
2,Mb_Sales-Med-N p#-144604#1 1 @ns PUCIa#0000061...,SP-1 70010013941,THE MITRE CORPORATION
3,Mb_Sales-Med-N p#-144604#1 1 @ns- PUCIa#000003...,SP-1 7700100114053,WILLIAMS SCOTSMAN W
4,Mb_Sales-Med-N p#-144604#1 1 @ns-PUCla#000001 ...,SP-1 7700100176570,TELVENT
5,Mb_Sales-Med-N p#-144604#11 @ns-PUCIa#00000316...,SP-1 770010018064,ANVICOM
6,Mb_Sales-Med-N p#-144604#1 1 @ns- PUCIa#-00000...,SP-1 700100175450,THOMSON FINANCIAL T
7,Mb_Sales-Med-N p#-144604#1 I @as- PUCIa#000006...,SP-1 70,IOO160580 ANEXINET A
8,Mb_Sales-Med-N p#-144604#1 1 @ns- PUCIa#-00000...,SP-1 7700100151530,ANEXINET
9,Mb_Sales-Med-N p#-144604#1 1 @ns-PUCIa#0000041...,SP-1 770010013020,TELVENT
10,Mb_Sales-Med-N p#-144604#1 1 @ns PUCIa#-000004...,SP-1 7700100122374,KELVIN DELIVATIVES K
11,Mb_Sales-Med-N p#-144604#1 1 @ns- PUCIa#000002...,SP-1 77001001541,WILLIAMS SCOTSMAN W
12,Mb_Sales-Med-N p#-144604#1 1 @ns- PUCIa#-00000...,SP-17700100119362,TANGOSOL INC T
13,Mb_Sales-Med-N p#-144604#1 1 @ns- PUCIa#-00000...,SP-17700100149962,_ BLUE DART
14,Mb_Sales-Med-Np#-144604#1 1 @as PUCIa#-0000041...,SP-17700100173171,ELECTRONIC DATA SYSTEMS
15,Mb_Sales-Med-N p#-144604#11 @ns- PUCIa\ 5,SP-1770010013398,ARIESCARGO
16,Mb_Sales-Med-N p#-144604#1 1 @ns- PUCIa#-00000...,SP-17700100134513,BAE SYSTEMS B
17,Mb_Sales-Med-N p#-144604#1 1 @ns- PUC1a#-00000...,SP-17700100174722,_ BAE SYSTEMS
18,Mb_Sales-Med-Np#-144604#11 @as PUCIa#-00000687...,SP-17700100166033,TANGOSOL INC T
19,Mb_Sales-Med-N p#-144604#1 1 @ns- PUCI a#-0000...,SP-1 770010011,86 HE MUNICENTER
20,Mb_Sales-Med-N p#-144604#1 1 @ns- PUCIa#-00000...,SP-17700100139391,WILLIAMS SCOTSMAN W
21,Mb_Sales-Med-N p#-144604#1 1 @ns- PUCIa#-00000...,SP-177001001359,S

In [32]:
main.to_excel('result3.xlsx')